---
- name: Transfer and execute a script.
  hosts: all
  tasks:
     - name: Transfer the script
       uri: url: http://www.example.com
     - name: Execute the script
       shell: echo "Hi! Tower is working."
