---
- name: Transfer and execute a script.
  hosts: all
  tasks:
  # Check that you can connect (GET) to a page and it returns a status 200
    - uri: url=http://www.example.com
    - name: Execute the script
        shell: echo "Hi! Tower is working."
