- name: Hello VR
  hosts: all
  tasks:
    - name: Hello VR
      debug:
        msg: "Hello VR!"
        msg: "System {{ inventory_hostname }}"
        
- hosts: all
  tasks:
    - name: Run ls.sh and output "ls /"
      script: ls.sh
      register: out

    - debug: var=out.stdout_lines
